version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    ports:
      - "3000:3000"

networks:
  node-network:
    driver: bridge